### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by Flurrywinde** [justahuman1/i3-grid#1]
I installed via pip successfully, but I got the below error. `pip3 install pyyaml` fixed it, but I thought I'd report the "bug" anyway, since you might want to add something about it to the readme. Plus maybe chmodding manager.sh and getting the rc file from the repo. Oh, and also, the `-h` option produces `usage: __main__.py [-h]...` 

```
$ pip3 install --user i3-grid
Collecting i3-grid
  Downloading https://files.pythonhosted.org/packages/a3/6b/6791175cfbb08a715bf15d1a7221ba982668a7849631aa1189ff475d4f75/i3_grid-0.2.3b2-py3-none-any.whl
Collecting i3-py (from i3-grid)
Installing collected packages: i3-py, i3-grid
Successfully installed i3-grid-0.2.3b2 i3-py-0.6.4
~/.config/i3grid $ curl https://raw.githubusercontent.com/justahuman1/i3-grid/master/rofi/manager.sh > manager.sh
~/.config/i3grid $ curl https://raw.githubusercontent.com/justahuman1/i3-grid/master/rofi/matrix.rasi > matrix.rasi
~/.config/i3grid $ chmod +x manager.sh
 ~/.config/i3grid $ python3 -m i3grid -h
Traceback (most recent call last):
  File "/home/kanon/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/kanon/anaconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/kanon/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/kanon/.local/lib/python3.7/site-packages/i3grid/__init__.py", line 2, in <module>
    from i3grid.grid import (
  File "/home/kanon/.local/lib/python3.7/site-packages/i3grid/grid.py", line 32, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by justahuman1** [comment]
Hi, thanks for the report. On Arch, pyYaml comes installed with the python distribution. I was not aware that it is a separate dependency. In that case, I think I will move away from yaml all together and implement a simple key value store (or JSON). 

Regarding the chmod and rc file, I will update that in the README (though the automated installation does that, I can understand the intent of doing it manually). Can you expand on the -h option issue?

**Comment by Flurrywinde** [comment]
Re: the -h issue, I just figured you might want to have it say `i3grid` or some such instead of `__main__.py`. Currently it looks like this:
```
usage: __main__.py [-h] [--cols COLS] [--rows ROWS]
                   [--offset OFFSET [OFFSET ...]] [--perc PERC]
                   [--target TARGET] [--multis MULTIS [MULTIS ...]]
                   [--port PORT] [--all] [--floating] [--noresize] [--nofloat]
                   <action> [<action> ...]
```
Sorry to nit pick! I really like this program, BTW. I'm sure I'll get a ton of use out of it. Thanks!

**Comment by Flurrywinde** [comment]
I found another little thing. Sorry! The readme says: `*This requires changing the `src_file` variable in the manager.sh rofi script.` Shouldn't that be `grid_src`?

**Comment by justahuman1** [comment]
You're helping make this better (it is still in beta), so no need to be sorry, I am thankful :). I will look into changing the header into the script name but I don't believe the standard `argparse` library allows for that. However, I will try and see how that can be implemented.

You are correct about `grid_src`. I didn't want to make a full commit for that small change so I was going to include that in the next.

**Comment by Flurrywinde** [comment]
Ah, cool. As for the script name, I think there's a `prog` parameter, e.g. `parser = argparse.ArgumentParser(prog='i3grid', description='<i3grid's description>')`

**Comment by justahuman1** [comment]
Thanks for that, I added the `prog` argument and it works! I also updated the config to jsonc and removed the yaml dependency all together. Before I upload it to the official Pypy and AUR, can you test it really quick? You will have to re-download the config as it has changed. I also updated the README with all the changes we discussed above.

[Link](https://test.pypi.org/project/i3-grid/)
Installation: `pip install -i https://test.pypi.org/simple/ i3-grid`

Edit: 
I tested it on 3 systems and it was working (none of which are Ubuntu). For now, I have pushed the changes to PyPy and AUR. Feel free to upgrade as usual, rather than from test-pypy. Instructions are also in the README.

**Comment by Flurrywinde** [comment]
Sure thing. I did all this, as well as uninstalled `pyyaml`, and it worked. Looks good!
